### ISSUE TITLE
Crashes upon attempting to stream the file

### ISSUE THREAD

**Issue by TheNoob27** [Androz2091/discord-data-package-explorer#17]
When trying to upload the package, I always receive the same error -

![error](https://user-images.githubusercontent.com/54063052/112756639-05ef1b80-8fde-11eb-9cf7-da382efe2c50.jpeg)

I'm using Safari on mobile but this also happens on Chrome

**Comment by Androz2091** [comment]
This is a Safari specific issue. Upgrade Chrome and it should work
