### ISSUE TITLE
Inaccurate numbers

### ISSUE THREAD

**Issue by Suspense4615** [Androz2091/discord-data-package-explorer#2]
Message counts under "top users" are off by a lot, I have ~5k with a friend but the explorer shows ~2k and I've seen people claiming the explorer missed users they talked a lot with. Not sure if it's an issue on your end or a limitation from the package file itself, so I thought reporting it would be best

**Comment by Pyker** [comment]
I think this is a problem with the package file itself, I noticed it's missing a lot of data for me as well (from the package itself)

**Comment by Androz2091** [comment]
Hello, thank you for opening this issue. I can confirm @Pyker's answer, it seems that some data is missing in my package too. I sent a mail to Discord, anyway they **have** to include all the messages in the package, so I think it's a bug going to be fixed.

**Comment by Androz2091** [comment]
I sent a new request and the new package I received by email was correct, all the messages were included... Maybe retry or send a mail to Discord so you can ask for a new package right now without waiting for the cooldown

**Comment by Androz2091** [comment]
I'm closing this, feel free to open a new issue if anyone has any news.

**Comment by Suspense4615** [comment]
Oh hey, sorry for the late response! I've requested a new package and the new data was much more accurate than before, so it's definitely an issue on Discord's end
