### ISSUE TITLE
TypeError: network error

### ISSUE THREAD

**Issue by ven** [Androz2091/discord-data-package-explorer#20]
When loading my package folder, I get this error. It's a fresh download from the Discord email, so not entirely sure what has gone wrong here. Just hangs on `loading your package file`.

Browser: Chrome
OS: macOS Big Sur

<img width="1389" alt="image" src="https://user-images.githubusercontent.com/46830208/113412399-0c034480-93b0-11eb-986b-f16dd08c4993.png">

**Comment by Androz2091** [comment]
This is weird. Can you retry? "Network error" means that a request to https://diswho.androz2091.fr has failed, I guess.

**Comment by ven** [comment]
Still getting the network error.

**Comment by Androz2091** [comment]
I tried using Chrome and a MacOS Big Sur computer and it worked perfectly. I guess it's because of the package... What is the size of the file?

**Comment by ven** [comment]
2.75GB folder

**Comment by Androz2091** [comment]
All right, perfect! I will try to see why it doesn't show an error message when you uploads something else than a zip file
