### ISSUE TITLE
Crash when i import my package

### ISSUE THREAD

**Issue by yoann56100** [Androz2091/discord-data-package-explorer#22]
![image](https://user-images.githubusercontent.com/33899467/115973676-2f588400-a557-11eb-9b66-b387a04c10ce.png)

**Comment by luisfelipesdn12** [comment]
@yoann56100 Can you check your file `account/user.json`?
I've deleted my ID and discriminator in that trying to reproduce, but it was still working.

Would be great if you describe more the steps to reproduce the error
