### ISSUE TITLE
[BUG] TypeError: Cannot read property 'stream' of null

### ISSUE THREAD

**Issue by Delta-official** [Androz2091/discord-data-package-explorer#27]
![Знімок екрана  о 13 32 43](https://user-images.githubusercontent.com/64544951/120100838-8ac7f400-c14b-11eb-8ce3-5c3542beaabd.png)
Does this everytime i try to upload

**Comment by luisfelipesdn12** [comment]
Hey @Delta-official what is your browser?
Also, can you try to upload a random `.zip` file and see if the error `Your package seems to be corrupted. Click or drop your package file here to retry` is returned?

**Comment by fixator10** [comment]
Same here, `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36 OPR/76.0.4017.177` (Opera)

For random `.zip` error is returned.

**Comment by Delta-official** [comment]
> Hey @Delta-official what is your browser?
> Also, can you try to upload a random `.zip` file and see if the error `Your package seems to be corrupted. Click or drop your package file here to retry` is returned?

I am using Opera on MacOS Mojave, on random zip package is corrupted message is displayed

**Comment by Delta-official** [comment]
> Thank you, @fixator10 @Delta-official! One last thing, it works when you click and select the file instead of dropping?

yes, it does

**Comment by luisfelipesdn12** [comment]
> > Thank you, @fixator10 @Delta-official! One last thing, it works when you click and select the file instead of dropping?
> 
> yes, it does

Great! It might be some incompatibility with the drop event on your browser/file/file manager.
Although, the correct behavior of the app would be to show an error message instead of just load forever.

On more time, thank you, @fixator10 and @Delta-official for the useful information :)

**Comment by luisfelipesdn12** [comment]
@fixator10 @Delta-official can you try it?

https://deploy-preview-30--ddpe.netlify.app/

**Comment by fixator10** [comment]
Seems to be fine. Shows proper error on drop, works via open prompt

**Comment by Androz2091** [comment]
All right, perfect :wink:
The preview has been deployed at **https://ddpe.androz2091.fr**! :tada:
Thanks again to @luisfelipesdn12 for the fix and thanks to you for reporting it!
