### ISSUE TITLE
[Run Issue] error: 'Chart' is not exported by node_modules\frappe-charts\dist\frappe-charts.min.umd.js, imported by node_modules\svelte-frappe-charts\src\components\base.svelte

### ISSUE THREAD

**Issue by SpoonMcForky** [Androz2091/discord-data-package-explorer#29]
I mean there are barely any instructions, not like there needs to be more, but it seems as though it's not on my end, other people I know are having this issue too.

**Comment by SpoonMcForky** [comment]
using yarn instead of npm worked ¯\_(ツ)_/¯

**Comment by busybox11** [comment]
Oh damn, I have the same issue with NPM and I'd like not to use yarn. Well, no luck for me.

**Comment by piks** [comment]
this is a repeat of issue #21, the solution to the issue is listed there, it has to do with an invalid import configuration
