### ISSUE TITLE
Some data is missing in the package file

### ISSUE THREAD

**Issue by Rjohn1277** [Androz2091/discord-data-package-explorer#34]
Heya, sorry if this is a repeat, I did see the previous post with a similar title but wanted to see if mine was for the same reason as well. When I attempt to go to the website (https://ddpe.androz2091.fr/) and put the package file I recieved from Discord into the website. It starts to load and hits 100% and then just stays at a blank screen and doesn't load anything. I saw the previous message stating something about a messages.csv file. I went to Package->Messages->(Picked a random file with a long string of numbers as there's a lot of them) and saw there was only a channel.json file. In every single one of them.

I'm guessing this is for the same reason as the previous post, but thought I'd post here in case it wasn't. I provided a screenshot of what the page looks like after I put the package file in the site

![Blank Site](https://user-images.githubusercontent.com/32545828/121461481-efb9f000-c97c-11eb-841a-cdd54fcd96fb.PNG)

**Comment by Androz2091** [comment]
Hello, indeed this is not a valid package. A messages.json file should be in each folder too. Can you send a message to Discord? (on their support website)
They **have** to include that file so I guess it's a bug.

**Comment by Rjohn1277** [comment]
> Hello, indeed this is not a valid package. A messages.json file should be in each folder too. Can you send a message to Discord? (on their support website)
> They **have** to include that file so I guess it's a bug.

I left the message on there, hopefully I get a reply relatively quickly, thanks for the help :)

**Comment by ABOATDev** [comment]
I have the same problem, I guess they won't send their "messages" file anymore

**Comment by Androz2091** [comment]
I've also sent a message, because these files were missing in my package too.

@ABOATDev they just... have to, from a legal point of view 🙃 
Otherwise, we can simply parse the analytics file. This will also work.

**Comment by Rjohn1277** [comment]
I've gotten a reply back from the support team. They've mentioned the issue is on their radar and their working on fixing it and will be sending out new data packages to replace the ones missing files. I should receive mine in about a week. I'll go ahead and close this issue now that I've received a reply back from the Support Team. Hopefully they fix this ASAP

**Comment by Androz2091** [comment]
Nice! Can you send a screenshot of their reply here?

**Comment by Androz2091** [comment]
I will let the issue opened so everyone can see it 👌

**Comment by Rjohn1277** [comment]
> Nice! Can you send a screenshot of their reply here?

Definitely, here's the reply I got back from them

![Discord Support Response](https://user-images.githubusercontent.com/32545828/121783491-e8f9cb80-cb7c-11eb-889a-7ddfa4b51e87.PNG)

**Comment by Androz2091** [comment]
All right, thank you! 😃

**Comment by Androz2091** [comment]
The issue has been fixed, new packages have been sent by Discord! v1.9.0 should be working fine for everyone!

**Comment by nigtwisj** [comment]
I received my new data package and I just tried it with the new data package and it doesn't seem to work. Is the update running on the website already or do I have to wait for a bit longer?

**Comment by Androz2091** [comment]
Yes, it is running on the website. Clear your cache and it will work. You can also use https://v190--ddpe.netlify.app
