### ISSUE TITLE
Assistance in self-hosting DDPE on shared web hosting.

### ISSUE THREAD

**Issue by WinglessWhistle** [Androz2091/discord-data-package-explorer#39]
I use Namecheap Shared Hosting (Stellar Plus Package) and would like to host ddpe on the website. Would I be able to get assistance in doing so?

**Comment by Androz2091** [comment]
Hello, sure, you may read <https://github.com/Androz2091/discord-data-package-explorer#installation> before and that's all. If you need more information, feel free to ask :wink:
