### ISSUE TITLE
(Suggestion) Show top 10 of words used with counts rather than just one favourite word

### ISSUE THREAD

**Issue by jack1142** [Androz2091/discord-data-package-explorer#4]
I think that it would be interesting to learn more than just one most used word and to also be able to see how many times they were used.

**Comment by vanishedvan** [comment]
#6

**Comment by jack1142** [comment]
Should be fixed by #6 and if it doesn't, I'll probably make a follow-up issue 😄

**Comment by Androz2091** [comment]
I added the tooltips!
