### ISSUE TITLE
Username and top users are Unknown

### ISSUE THREAD

**Issue by FayneAldan** [Androz2091/discord-data-package-explorer#41]
Continuation of #40. I've tried redownloading the package and using the tool with multiple browsers, including MS Edge and Brave Browser, without success.

**Comment by awulkan** [comment]
I'm having the same problem with data I just requested from Discord.

**Comment by Djassie18698** [comment]
I also have the same problem, everything works but my users are all unknown

**Comment by Androz2091** [comment]
This is now fixed. Can you retry and post your updated results here please?

**Comment by awulkan** [comment]
The top users and top channels are okay for me now, but everything else is broken. I'm seeing the stats of the demo account.

**Comment by Djassie18698** [comment]
It indeed works now, thankyou!

**Comment by Androz2091** [comment]
Perfect, then I'm closing the issue
