### ISSUE TITLE
Site does not load my data at all

### ISSUE THREAD

**Issue by MrJacz** [Androz2091/discord-data-package-explorer#5]
I have tried Chrome, Edge, Firefox on laptop, desktop and mobile an get the same error. Everyone else i know works fine but not me. Now maybe its got something to do with my account being 5 years old? im not sure

![image](https://user-images.githubusercontent.com/23615291/109310203-56b50c80-7898-11eb-97e4-c2237205f0ca.png)

**Comment by Androz2091** [comment]
Hello, there seems to be a problem with your package file (and with the site). In the `messages` directory, a sub-folder should be empty or `messages.csv`/`channel.json` are missing. I will fix the issue, but it would be nice to identify the case where these files are missing... 🤔

**Comment by Androz2091** [comment]
I deployed a patch. You can try again, and some debug in the console will show up if some files can't be read.

**Comment by MrJacz** [comment]
Okay so one of the folders in messages has a channel.json but no messages.csv
After deleting that folder the app works perfectly
![image](https://user-images.githubusercontent.com/23615291/109364678-6dcd1c00-78e3-11eb-8d9a-4b9b06d7f010.png)

**Comment by Stonedestroyer** [comment]
```
extractor.js:55 Uncaught (in promise) TypeError: Cannot set property 'ondata' of undefined
    at extractor.js:55
    at new Promise (<anonymous>)
    at readAnalyticsFile (extractor.js:50)
    at extractData (extractor.js:218)
(anonymous) @ extractor.js:55
readAnalyticsFile @ extractor.js:50
extractData @ extractor.js:218
Promise.then (async)
handleFile @ Loader.svelte:38
async function (async)
handleFile @ Loader.svelte:21
handleDrop @ Loader.svelte:53
```
Is this related?

**Comment by Androz2091** [comment]
@Stonedestroyer, what is the name of the file located in the `activity/analytics` folder?

**Comment by Stonedestroyer** [comment]
There is only a folder there "tns/events-2021-00000-of-00001.json". It may be cause I have disabled analytics but wish to get post data still.

**Comment by Androz2091** [comment]
Yes indeed so we can't retrieve this data. I pushed a fix so it now shows N/A instead of crashing
