### ISSUE TITLE
Remove Deleted Users from our Top DM'ed list

### ISSUE THREAD

**Issue by SilentSerenityy** [Androz2091/discord-data-package-explorer#61]
It'd be pretty useful to remove any deleted users from the top 10 people that have been DM'ed
Could easily be done by checking the name "Deleted User (random characters)" and the default pfp

For now, one could manually delete Deleted Users from their package by looking up their channel id of the DM and deleting that folder, but not everyone has access to the DM of their friend's deleted account

**Comment by ErginDapaj** [comment]
Don't!
It brings up memories.

**Comment by TheChilliPL** [comment]
The weird thing is I, instead of `Deleted User (random gibberish)`, get this:
![image](https://user-images.githubusercontent.com/18823939/194750945-e6aa12e3-e2f1-4168-8121-33647b5a2d30.png)

**Comment by Androz2091** [comment]
This should not happen in most recent versions. We will keep deleted users though.
