### ISSUE TITLE
[Request] Desktop App

### ISSUE THREAD

**Issue by JinstoNim** [Androz2091/discord-data-package-explorer#67]
The most I can see is that you can make your own website with its code, but I don't see an ability to turn it into a separate desktop application that can run without a browser.

**Comment by lucsoft** [comment]
![image](https://user-images.githubusercontent.com/11093382/194245582-b5677710-5377-45a9-af66-e8b4eea5f196.png)

You can always install it as an PWA 

Just Create a Shortcut an make sure to enable "Open as Window"
<img width="498" alt="image" src="https://user-images.githubusercontent.com/11093382/194245704-0711dffe-223c-4e96-9510-33d60e45dbdb.png">

Then it runs outside the normal browser

with the help of a pwa-manifest we could also make a install popup for easier finding

**Comment by Androz2091** [comment]
We will not maintain a desktop app - too much work for this project atm.
