### ISSUE TITLE
Bug, duplication top user 

### ISSUE THREAD

**Issue by Kaputchino** [Androz2091/discord-data-package-explorer#68]
By using this app, one of my top user is dupliacted, I tried with an other app and it worked fine.
[https://www.mediafire.com/view/yisnu3sq2hjgqgv/imageDIs.png/file](url)

**Comment by Kaputchino** [comment]
sry english, isn't my native language

**Comment by Androz2091** [comment]
File is missing, please upload directly on GitHub
